services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogdb
      MYSQL_USER: quarkus
      MYSQL_PASSWORD: quarkus
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-nw

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/blogdb
      KC_DB_USERNAME: quarkus
      KC_DB_PASSWORD: quarkus
      KC_HOSTNAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - blog-nw

  quarkus-app:
    image: blog-app # Use the actual built image name
    environment:
      QUARKUS_DATASOURCE_DB_KIND: mysql
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/blogdb
      QUARKUS_DATASOURCE_USERNAME: quarkus
      QUARKUS_DATASOURCE_PASSWORD: quarkus
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/blog-realm
      QUARKUS_OIDC_CLIENT_ID: blog-client
      QUARKUS_OIDC_CREDENTIALS_SECRET: iIulodrT0jaIYHNkTzZOoM7sokDwcWyx
    depends_on:
      - mysql
      - keycloak
    ports:
      - "8081:8081" # Expose the Quarkus app on port 8081
    networks:
      - blog-nw

networks:
  blog-nw:
    external: true

volumes:
  mysql_data:
