version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=dev-mem
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - 3306:3306

  blog-system:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm  # Path to Dockerfile.jvm
    ports:
      - 8081:8080
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mysql://mysql:3306/mydb
      QUARKUS_DATASOURCE_USERNAME: myuser
      QUARKUS_DATASOURCE_PASSWORD: mypassword
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/blog-realm
      QUARKUS_OIDC_CLIENT_ID: blog-client
      QUARKUS_OIDC_CREDENTIALS_SECRET: iIulodrT0jaIYHNkTzZOoM7sokDwcWyx
    depends_on:
      - keycloak
      - mysql
